urlGithub: https://github.com
usuarioGithub: LucasBertiDev
repositorios:
  - nome: postgres
  - nome: accounts
  - nome: linkerd-viz
  - nome: lancamentos
  - nome: argocd-applications
  - nome: argocd-repositories-helm
  - nome: argocd-helm-chart
  - nome: cartoes
  - nome: prometheus-helm-chart
  - nome: kubernetes-persistent-volumes
  - nome: grafana